[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
blacksmith = "4vbkSNKb9hx4DVe1md2CBzLwLwE8xsKAwBALe8CrNxVx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
